var numbers = [1, 3, 4, 4];
numbers.push(4);
console.log(numbers);
var fruits = ["apple", "bannana"];
fruits.push("mango");
console.log(fruits);
var colors = ["hello", "bye"];
//colors.push("yellow");
var mixed = ["hello", 42];
mixed.push(2888);
mixed.push("typescript");
console.log(mixed);
